on: [push]
enable-email-notifications: true
jobs:
  check:
    strategy:
      matrix:
        os: [ node-lts, macos ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/DeterminateSystems/nix-installer-action@main
        if: matrix.os == 'node-lts'
      - run: nix flake check
