on: [push]
enable-email-notifications: true
jobs:
  check:
    strategy:
      matrix:
        os: [ docker, macos ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/DeterminateSystems/determinate-nix-action@v3
        if: matrix.os == 'docker'
      - run: nix flake check
